// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGProductionIndicatorComponent.h"

UFGProductionIndicatorComponent::UFGProductionIndicatorComponent(){ }
void UFGProductionIndicatorComponent::OnUnregister(){ }
void UFGProductionIndicatorComponent::OnRegister(){ }
void UFGProductionIndicatorComponent::TickComponent( float deltaTime, enum ELevelTick tickType, FActorComponentTickFunction *thisTickFunction ){ }
void UFGProductionIndicatorComponent::ResetIndicatorStatus(){ }
